# Setting the variable based on NEXUS_GRAPHICS_API
set(NEXUS_GRAPHICS_API_DEFINITIONS)

if(${NEXUS_GRAPHICS_API} STREQUAL "OFF")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_NONE)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "ALL")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_SOFT)
    if(${NEXUS_PLATFORM} STREQUAL "Desktop")
        list(APPEND NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_33)
    else()
        list(APPEND NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_ES2)
    endif()

elseif(${NEXUS_GRAPHICS_API} STREQUAL "SOFT")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_SOFT)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "GL 1.1")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_11)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "GL 2.1")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_21)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "GL 3.3")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_33)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "GL 4.3")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_43)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "GL ES2")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_ES2)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "GL ES3")
    set(NEXUS_GRAPHICS_API_DEFINITIONS -DGRAPHICS_API_OPENGL_ES3)

endif()

# Pre-defining graph API usage indicators
set(NEXUS_SUPPORT_SOFTWARE_RASTERIZER OFF)
set(NEXUS_SUPPORT_OPENGL OFF)

# Detection of the type of graphics API used
if (${NEXUS_GRAPHICS_API} STREQUAL "ALL")
    set(NEXUS_SUPPORT_SOFTWARE_RASTERIZER ON)
    set(NEXUS_SUPPORT_OPENGL ON)

elseif(${NEXUS_GRAPHICS_API} STREQUAL "SOFT")
    set(NEXUS_SUPPORT_SOFTWARE_RASTERIZER ON)

elseif(NEXUS_GRAPHICS_API MATCHES ".*GL.*")
    set(NEXUS_SUPPORT_OPENGL ON)

endif()

# Applying the Graph API type as a definition
list(APPEND NEXUS_GRAPHICS_API_DEFINITIONS
    SUPPORT_SOFTWARE_RASTERIZER=$<BOOL:${NEXUS_SUPPORT_SOFTWARE_RASTERIZER}>
    SUPPORT_OPENGL=$<BOOL:${NEXUS_SUPPORT_OPENGL}>)
