set(NEXUS_PLATFORM_DEFINITIONS)

if(${NEXUS_PLATFORM} STREQUAL "Desktop")
    list(APPEND NEXUS_PLATFORM_DEFINITIONS -DPLATFORM_DESKTOP)
elseif(${NEXUS_PLATFORM} STREQUAL "Android")
    list(APPEND NEXUS_PLATFORM_DEFINITIONS -DPLATFORM_ANDROID)
endif()
